# Generated by Django 2.1.7 on 2019-02-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='DOB',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
