# Generated by Django 2.1.7 on 2019-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190223_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='DOB',
            field=models.DateField(),
        ),
    ]
